name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: autor
      run: autoreconf --install
      working-directory: ./linux/command line
    - name: configure
      run: ./configure
      working-directory: ./linux/command line
    - name: make
      run: make
      working-directory: ./linux/command line
    - name: package
      run: make distcheck
      working-directory: ./linux/command line
